---
title: "Homework 4"
author: "Nikole Vannest, Emiliano Espinoza, Elena Oritz"
date: "5/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)

warming <- read.csv(here("data", "warming.csv"))
damages <- read.csv(here("data", "damages.csv"))
```

1. Create a quadratic damage function relating the `$$` value of damages to the change in global mean temperature. 

```{r preliminary data visualization}
#damages %>% ggplot(aes(x = warming, y = damages)) + geom_point() 

```

```{r building quadratic function}
#y = ax^2 + bx + c

damages_quadratic <- cbind("warming_sq" = (damages$warming)^2, damages)
damages_lm <- lm(damages ~ warming_sq + warming + 0, data = damages_quadratic) #linear model
a <- damages_lm$coefficients[["warming_sq"]] #coefficient a
b <- damages_lm$coefficients[["warming"]] #coefficient b

damages_lm2 <- a*damages_quadratic$warming_sq + b*damages_quadratic$warming #Calculating quadratic equation

damages_quadratic %>% ggplot(aes(x = warming, y = damages)) +
  geom_point() +
  geom_line(aes(y = damages_lm2)) +
  ylab("Damage") +
  xlab("Warming scenario") +
  theme_minimal()+
  ggtitle("Estimating Damages Under Warming Scenarios")

```

2. Use warming data to predict damages under baseline and pulse scenarios.

```{r, non-pulse scenario}
damages_baseline <- a*((warming$warming_baseline)^2) + b*warming$warming_baseline

warming %>% ggplot(aes(x = year, y = damages_baseline)) +
  geom_point() +
  geom_line(aes(y = damages_baseline)) +
  ylab("Damages ($)") +
  xlab("Year") +
  theme_minimal()+
  ggtitle("Estimating Damages Under Warming Baseline Scenario")

```

```{r, pulse scenario}
damages_pulse <- a*((warming$warming_pulse)^2) + b*warming$warming_pulse

warming %>% ggplot(aes(x = year, y = damages_pulse)) +
  geom_point() +
  geom_line(aes(y = damages_pulse)) +
  ylab("Damages ($)") +
  xlab("Year") +
  theme_minimal()+
  ggtitle("Estimating Damages Under Pulse Warming Scenario")
```


```{r, difference between pulse and non-pulse scenarios}

difference_scenario <- damages_pulse - damages_baseline

warming %>% ggplot(aes(x = year, y = difference_scenario)) +
  geom_point() +
  geom_line(aes(y = difference_scenario)) +
  ylab("Damages ($)") +
  xlab("Year") +
  theme_minimal()+
  ggtitle("Estimating Differences in Damages Between Baseline and Pulse")
```


```{r, Difference in damages per ton CO2}
per_ton <- difference_scenario / 35000000000 #to get per ton CO2

warming %>% ggplot(aes(x = year, y = per_ton)) +
  geom_point() +
  geom_line(aes(y = per_ton)) +
  ylab("Damages ($/ton CO^2)") +
  xlab("Year") +
  theme_minimal()+
  ggtitle("Estimating Differences in Damages Between Baseline and Pulse in Per ton CO^2 Emitted")

```
 
3. Calcuate the SCC against the discount rate for a reasonable range of discount rates.\
  
  - Obama: 3%
  - NY State: 2%

```{r}
#cost/(1+rate)^year

SCC_2 <- (per_ton)/(1+0.02)^(warming$X)

```







